Repository CodeYourFuture/over-the-Line, pull requests merged in 2020-08, with the labels that each got.

#3 Backend folder
  backend/.gitignore
  backend/app.js
  backend/bin/www
  backend/package-lock.json
  backend/package.json
  backend/public/stylesheets/style.css
  backend/routes/index.js
  backend/routes/users.js
  backend/views/error.jade
  backend/views/index.jade
  backend/views/layout.jade
Labels: BE

#4 Frontend_folder
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/serviceWorker.js
  frontend/src/setupTests.js
Labels: FE

#1 add_gitignore
  .gitignore
Labels: wontfix

#8 Update README.md
  README.md
Labels: documentation

#9 Feature/install react router
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/logo.svg
  frontend/src/setupTests.js
Labels: FE

#12 Feature/install esLint and esLint Prettier
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
Labels: FE

#10 installed react bootstrap
  frontend/package-lock.json
  frontend/package.json
Labels: FE

#11 create pages
  frontend/package-lock.json
  frontend/package.json
  frontend/products.json
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/assets/logo.png
  frontend/src/assets/products.json
  frontend/src/components/ArtistPage/ArtistPage.js
  frontend/src/components/ArtistsPage/ArtistsPage.js
  frontend/src/components/HomePage/HomePage.js
  frontend/src/components/ProductPage/ProductPage.js
  frontend/src/components/ProductsPage/ProductsPage.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/serviceWorker.js
Labels: FE

#7 feature/add ESlint and install mongoDB
  backend/.eslintrc.json
  backend/package-lock.json
  backend/package.json
  backend/routes/index.js
  backend/routes/users.js
Labels: BE

#17 add Icons and product page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/ProductPage/ProductPage.js
Labels: FE

#19 skip single product page
  frontend/src/App.js
  frontend/src/components/CategoriesPage/CategoriesPage.js
Labels: FE

#20 bug fixed
  frontend/src/assets/products.json
  frontend/src/components/ArtistsPage/ArtistsPage.js
Labels: FE

#24 Feature/redesign footer
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/assets/products.json
  frontend/src/components/ArtistsPage/ArtistsPage.js
  frontend/src/components/CategoriesPage/CategoriesPage.js
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/Footer.js
  frontend/src/components/NavBar/NavBar.js
  frontend/src/components/ProductPage/ProductPage.js
  frontend/src/components/ProductsPage/ProductsPage.js
Labels: FE

#21 Feature backend-get
  README.md
  backend/.gitignore
  backend/models/artists.js
  backend/package-lock.json
  backend/package.json
  backend/routes/artists.js
  backend/server.js
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/README.md
  frontend/products.json
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/components/ArtistPage/ArtistPage.js
  frontend/src/constant/index.js
  frontend/src/index.js
  frontend/src/utils/index.js
Labels: BE

#27 connect social links
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/Footer.js
  frontend/src/components/NavBar/NavBar.js
Labels: FE

#26 back to top btn
  frontend/src/App.css
  frontend/src/components/BackToTop/BackToTop.css
  frontend/src/components/BackToTop/BackToTop.js
  frontend/src/components/HomePage/HomePage.js
  frontend/src/components/NavBar/NavBar.css
  frontend/src/components/ProductPage/ProductPage.css
  frontend/src/components/ProductPage/ProductPage.js
Labels: FE

#28 fix back to top
  frontend/src/App.css
  frontend/src/assets/bubble.svg
  frontend/src/components/BackToTop/BackToTop.css
  frontend/src/components/BackToTop/BackToTop.js
  frontend/src/components/CategoriesPage/CategoriesPage.css
  frontend/src/components/CategoriesPage/CategoriesPage.js
  frontend/src/components/Footer/Footer.js
  frontend/src/components/HomePage/HomePage.js
  frontend/src/components/ProductPage/ProductPage.css
Labels: FE
